plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.francesco.citapluus'
    compileSdk 34

    defaultConfig {
        applicationId "com.francesco.citapluus"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        multiDexEnabled true
    }

    buildTypes {
        debug {
            minifyEnabled false
            buildConfigField "boolean", "USE_MOCK", "true"
        }
        release {
            minifyEnabled false
            buildConfigField "boolean", "USE_MOCK", "false"
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}
dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.core:core-ktx:1.12.0"
    implementation "com.google.android.material:material:1.12.0"
    implementation "androidx.constraintlayout:constraintlayout:2.2.0"
    implementation "androidx.preference:preference-ktx:1.2.1"

    implementation "androidx.lifecycle:lifecycle-runtime:2.6.2"
    implementation "androidx.lifecycle:lifecycle-livedata:2.6.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.6.2"

    implementation "com.google.android.gms:play-services-maps:18.1.0"
    implementation "com.google.android.gms:play-services-location:21.0.1"
    implementation "com.google.android.libraries.places:places:3.5.0"

    implementation "com.squareup.retrofit2:retrofit:2.11.0"
    implementation "com.squareup.retrofit2:converter-gson:2.11.0"
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.12.0"


    implementation "com.google.code.gson:gson:2.10.1"

    debugImplementation "com.squareup.okhttp3:mockwebserver:4.12.0"

    implementation platform('com.google.firebase:firebase-bom:33.1.0')

    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-messaging'
}

